<?php

namespace OC\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function getUsersList($username)
  {
    $qb = $this->createQueryBuilder('e');
    $qb->select('DISTINCT  e.username')->where('e.username LIKE :username')->setParameter('username', $username.'%');

    $arrayQb = $qb->getQuery()->getArrayResult();

    $array = array();

    foreach ($arrayQb as $value) {
      $array[] = $value;
    }

    return $array;
  }

  public function getUsersCountByRole($role)
  {
      $qd = $this->createQueryBuilder('u')
          ->andWhere('u.roles LIKE :roles')
          ->setParameter('roles', '%'.$role.'%')
          ->select('count(u.id)')
          ;

      return $qd->getQuery()->getSingleScalarResult()
      ;
  }


}
