<?php

namespace OC\NAOBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{
  public function listeEspece($espece)
  {
    $qb = $this->createQueryBuilder('e');
    $qb->select('DISTINCT e.nomVern')->where('e.nomVern LIKE :espece')->setParameter('espece', $espece.'%');

    $arrayQb = $qb->getQuery()->getArrayResult();

    $array = array();

    foreach ($arrayQb as $value) {
      $array[] = $value;
    }

    return $array;
  }

  public function famille($espece)
  {
    $qb = $this->createQueryBuilder('e');
    $qb->select('DISTINCT e.famille')->where('e.nomVern = :espece')->setParameter('espece', $espece);

    return $qb->getQuery()->getSingleScalarResult();
  }
}
